#!/bin/bash

# JLINK_VM_OPTIONS=
# DIR=`dirname $0`
# $DIR/java $JLINK_VM_OPTIONS -m fr.glhez.jtools.warextractor/fr.glhez.jtools.warextractor.MainCommand $@


# jtools-warextractor=fr.glhez.jtools.warextractor/fr.glhez.jtools.warextractor.MainCommand

declare HERE="$(realpath ${0%/*})"

declare JAVA_PATH="$HERE/target/maven-jlink/bin/java" 
declare JARS_PATH="$HERE/target/dependency"

"$JAVA_PATH" --add-reads org.apache.logging.log4j=ALL-UNNAMED \
             --module-path "$JARS_PATH" \
             -Dsun.stdout.encoding=utf-8 \
             -D_log4j2.debug \
             -m fr.glhez.jtools.warextractor/fr.glhez.jtools.warextractor.MainCommand $@
